namespace Taskpilot.API.Services;

/// <summary>
/// Stores file bytes on the local disk, under "uploads" in the content root. The default
/// for development. NOT suitable for a hosting platform with an ephemeral filesystem —
/// configure S3 storage there instead.
/// </summary>
public class LocalFileStorage : IFileStorage
{
    private readonly string _uploadsRoot;
    private readonly ILogger<LocalFileStorage> _logger;

    public LocalFileStorage(IWebHostEnvironment env, ILogger<LocalFileStorage> logger)
    {
        _logger = logger;
        _uploadsRoot = Path.Combine(env.ContentRootPath, "uploads");
        Directory.CreateDirectory(_uploadsRoot);
    }

    /// <inheritdoc />
    public string Name => "local-disk";

    /// <inheritdoc />
    public async Task SaveAsync(string storedName, Stream content, string contentType, CancellationToken cancellationToken = default)
    {
        await using var file = File.Create(PathFor(storedName));
        await content.CopyToAsync(file, cancellationToken);
    }

    /// <inheritdoc />
    public Task<Stream?> OpenReadAsync(string storedName, CancellationToken cancellationToken = default)
    {
        var path = PathFor(storedName);
        if (!File.Exists(path))
        {
            _logger.LogWarning("File metadata exists but the bytes are missing on disk. StoredName: {StoredName}", storedName);
            return Task.FromResult<Stream?>(null);
        }

        return Task.FromResult<Stream?>(File.OpenRead(path));
    }

    /// <inheritdoc />
    public Task DeleteAsync(string storedName, CancellationToken cancellationToken = default)
    {
        var path = PathFor(storedName);
        if (File.Exists(path))
            File.Delete(path);

        return Task.CompletedTask;
    }

    /// <summary>
    /// Resolves the key to a path inside the uploads folder. The key is generated by us
    /// (a GUID plus the extension), but this still refuses anything with a directory
    /// separator so a crafted key can never escape the folder.
    /// </summary>
    private string PathFor(string storedName)
    {
        var safeName = Path.GetFileName(storedName);
        if (string.IsNullOrWhiteSpace(safeName) || safeName != storedName)
            throw new ArgumentException("Invalid stored file name.", nameof(storedName));

        return Path.Combine(_uploadsRoot, safeName);
    }
}
